library(arulesViz)
data(Groceries)
rules <- apriori(Groceries, parameter=list(support=0.005, confidence=0.5))
rules
plot(rules)
plot(rules, shading="order", control=list(main = "Two-key plot",col=rainbow(5)))
subrules <- subset(rules, lift>2.5)
subrules
plot(subrules, method="matrix", measure="lift")
plot(subrules, method="matrix3D", measure="lift")
plot(rules, method="grouped")
plot(rules, method = "grouped", control = list(k = 50))
subrules2 <- sample(rules, 10)
plot(subrules2, method="graph")
plot(subrules2, method="graph", control=list(layout=igraph::in_circle()))
plot(subrules2, method="graph", control=list(layout=igraph::with_graphopt(spring.const=5, mass=50)))
plot(subrules2, method="graph", control=list(type="itemsets"))
plot(subrules2, method = "paracoord")
plot(subrules2, method = "paracoord", control = list(reorder = TRUE))
oneRule <- sample(rules, 1)
inspect(oneRule)
plot(oneRule, method = "doubledecker", data = Groceries)
itemsets <- eclat(Groceries, parameter = list(support = 0.02, minlen=2))
plot(itemsets)
plot(itemsets, method="graph")
itemsets <- eclat(Groceries, parameter = list(support = 0.03, minlen=2))
plot(itemsets, method="graph")
itemsets <- eclat(Groceries, parameter = list(support = 0.04, minlen=2))
plot(itemsets, method="graph")
plot(itemsets, method="paracoord", control=list(alpha=.5, reorder=TRUE))
quality(itemsets) <- interestMeasure(itemsets, trans=Groceries)
head(quality(itemsets))
plot(itemsets, measure=c("support", "allConfidence"), shading="lift",control = list(col=rainbow(7)))
rules<-apriori(data=Groceries, parameter=list(supp=0.001,conf = 0.15,minlen=2),
               appearance = list(default="rhs",lhs="whole milk"),
               control = list(verbose=F))
rules<-sort(rules, decreasing=TRUE,by="confidence")
inspect(rules[1:5])
library(arulesViz)
plot(rules,method="graph",engine = 'default',shading=NA)
rules<-apriori(data=Groceries, parameter=list(supp=0.005,conf = 0.08),
               appearance = list(default="lhs",rhs="butter"),
               control = list(verbose=F))
rules<-sort(rules, decreasing=TRUE,by="confidence")
inspect(rules[1:5])
library(arulesViz)
plot(rules,method="graph",engine = 'default',shading=NA)
itemFrequencyPlot(Groceries,topN=20,type="absolute")

